### ISSUE TITLE
PVB是怎么计算的呢？

### ISSUE THREAD

**Issue by FredericJump** [TorchOPC/TorchLitho#3]
你好，我阅读了你的论文Ultra-Fast Source Mask Optimization via Conditional Discrete Diffusion，结合你给出的代码，我想知道PVB在这个过程中是如何计算的呢？在ICCAD2013中，PVB的定义下，其与dose和defocus有关，但是在你的litho中的Function下，reciepe中的dose并没有参加到实际的运算中（也有可能我检查不仔细，不好意思）。defocus实际是多少纳米，这一点我也挺疑惑的，如果能告知，万分感谢！
下面是我的邮箱 FredericJump@outlook.com，希望能得到回复！

**Comment by FredericJump** [comment]
查看了你最新的的论文Efficient Bilevel Source Mask Optimization后，我发现你对PVB的处理是用了dmin和dmax来近似的，是否意味着使用Abbe成像时，defocus和focus都是恒等于0的，这一点能探讨一下原因吗？你用的数值大概是什么范围可以告知吗？

**Comment by dekura** [comment]
Hi @FredericJump, please discuss issue in English for boarder communication.
 Regarding the PVB consideration, which is following the ICCAD 2013 paper by S. Banerjee, Z. Li and S. R. Nassif. T
he current version has defocus and focus set to 0, but you can use other hyperparameters if you like. Thank you.



> S. Banerjee, Z. Li and S. R. Nassif, "ICCAD-2013 CAD contest in mask optimization and benchmark suite," 2013 IEEE/ACM International Conference on Computer-Aided Design (ICCAD), San Jose, CA, USA, 2013, pp. 271-274, doi: 10.1109/ICCAD.2013.6691131. keywords: {Semiconductor device modeling;Resists;Optimization;Layout;Shape;Optical imaging;Benchmark testing},

**Comment by dekura** [comment]
@FredericJump May I know your institution and what kind of project you are working on? We can discuss more!

You can connect me with email cgjcuhk@gmail.com

**Comment by FredericJump** [comment]
Thanks for your reply and suggestion! I will take notice next time.
