### ISSUE TITLE
Some question about optical model

### ISSUE THREAD

**Issue by longtimenosee910** [TorchOPC/TorchLitho#4]
Hi, @dekura ,I am a graduate student,major in Computional Lithography(optical).Do you can recommend some book/paper that about vector model to me?Thank u very much.
Best wish!
Wang

**Comment by dekura** [comment]
> Hi, @dekura ,I am a graduate student,major in Computional Lithography(optical).Do you can recommend some book/paper that about vector model to me?Thank u very much.
> 
> Best wish!
> 
> Wang 

Not project related. Please close the issue.

For research discussion, please contact by email.

**Comment by longtimenosee910** [comment]
Thank you very much!
